version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: device_app
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3306:3306"
    networks:
      - device-network

  app:
    container_name: device_app
    depends_on:
      - mysqldb
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "9099:80"
    environment:
      DB_PASSWORD: 12345
      DB_NAME: device_app
      DB_USERNAME: root
      DB_HOST: mysqldb
    networks:
      - device-network

networks:
  device-network:
    driver: bridge